### ISSUE TITLE
MNIST Convolutional sample not working

### ISSUE THREAD

**Issue by nmilosev** [jdermody/brightwire#12]
Hey Jack,

when running this example, I get an error telling me that two matrices cannot be multiplied because of incorrect dimensions: `1024x10` and `64x10` or similarly, can't remember exactly. 

I rolled over to some previous version of the example class and it works, probably the architecture is somehow gone wrong.

Thanks for your help!

**Comment by jdermody** [comment]
Hey

I just tried downloading the latest version from github and running the CNN sample and it seems to be working. Can you check that you have the latest version of the code?

![image](https://user-images.githubusercontent.com/1952388/31252204-29ba4180-aa6c-11e7-8f38-4e2b28b11bf6.png)

Cheers,
Jack

**Comment by nmilosev** [comment]
I'm running on a CPU for now, that's probably the only difference.

Stack trace:
```
System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=Matrix dimensions must agree: op1 is 64x10, op2 is 64x1024.
  Source=MathNet.Numerics
  StackTrace:
   at MathNet.Numerics.LinearAlgebra.Matrix`1.Subtract(Matrix`1 other)
   at BrightWire.LinearAlgebra.CpuMatrix.Subtract(IMatrix matrix) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\LinearAlgebra\CpuMatrix.cs:line 143
   at BrightWire.ExecutionGraph.ErrorMetric.OneHotEncoding.CalculateGradient(IContext context, IMatrix output, IMatrix targetOutput) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\ErrorMetric\OneHotEncoding.cs:line 12
   at BrightWire.ExecutionGraph.Action.Backpropagate.Execute(IGraphData input, IContext context) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Action\Backpropagate.cs:line 31
   at BrightWire.ExecutionGraph.Node.Helper.ExecuteForwardAction.ExecuteForward(IContext context) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Node\Helper\ExecuteForwardAction.cs:line 21
   at BrightWire.ExecutionGraph.Node.NodeBase.ExecuteForward(IContext context, Int32 channel) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Node\NodeBase.cs:line 105
   at BrightWire.ExecutionGraph.Engine.Helper.TrainingEngineContext.ExecuteNext() in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Engine\Helper\TrainingEngineContext.cs:line 93
   at BrightWire.ExecutionGraph.Engine.TrainingEngine._Train(IExecutionContext executionContext, ILearningContext learningContext, IMiniBatchSequence sequence) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Engine\TrainingEngine.cs:line 174
   at BrightWire.ExecutionGraph.Engine.TrainingEngine._Train(IExecutionContext executionContext, ILearningContext learningContext, IMiniBatch batch) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Engine\TrainingEngine.cs:line 158
   at BrightWire.ExecutionGraph.Engine.TrainingEngine.<>c__DisplayClass14_0.<Train>b__0(IMiniBatch batch) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Engine\TrainingEngine.cs:line 94
   at BrightWire.ExecutionGraph.Helper.MiniBatchProvider.MiniBatchOperation.Execute(IExecutionContext executionContext) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Helper\MiniBatchProvider.cs:line 29
   at BrightWire.ExecutionGraph.Engine.TrainingEngine.Train(IExecutionContext executionContext, Action`1 batchCompleteCallback) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExecutionGraph\Engine\TrainingEngine.cs:line 101
   at BrightWire.ExtensionMethods.Train(IGraphTrainingEngine engine, Int32 numIterations, IDataSource testData, IErrorMetric errorMetric, Action`1 onImprovement, Int32 testCadence) in C:\Users\nmilosev\Downloads\brightwire-master\BrightWire.Source\ExtensionMethods.ExecutionGraph.cs:line 33
   at BrightWire.SampleCode.Program.MNISTConvolutional(String dataFilesPath, String outputModelPath) in C:\Users\nmilosev\Downloads\brightwire-master\SampleCode\MNISTConvolutional.cs:line 77
   at BrightWire.SampleCode.Program.Main(String[] args) in C:\Users\nmilosev\Downloads\brightwire-master\SampleCode\Program.cs:line 84

```

**Comment by nmilosev** [comment]
I can confirm that the issue only appears when running without CUDA.

Weird!

**Comment by nmilosev** [comment]
![error](https://user-images.githubusercontent.com/11432491/31290806-1700d740-aace-11e7-8162-8f0ea184f731.png)

I am now getting this exact error on GPU too, for what it's worth MNIST example works fine (without CNNs).

**Comment by jdermody** [comment]
Hi Nemanja

You are quite correct - I tested it using the release version of the GPU provider which swallowed the error (which I think is okay as the release version is optimised for speed). But future note to self: always use the debug version to check for problems ; )

Anyway, as you found, the network size for the final layer was wrong and is now fixed.

Thanks,
Jack

**Comment by nmilosev** [comment]
Thank you Jack, I tried it and it works! :)

Cheers,
Nemanja
